import type { WatchModel } from "@/types/watch";

export const DEFAULT_MODELS: WatchModel[] = [
  {
    id: "model-rolex-submariner",
    brand: "Rolex",
    name: "Submariner",
    heroImage: "",
    notes: "The most recognizable dive watch ever made. Two personalities — the clean no-date and the practical date. Both wear identically on the wrist. The difference is philosophical.",
    reactionTags: [],
    topPickVariantId: null,
    rank: 1,
    variants: [
      {
        id: "var-sub-124060",
        modelId: "model-rolex-submariner",
        reference: "124060",
        label: "No-Date · Black",
        size: "41mm",
        dialColor: "Black",
        strapType: "bracelet",
        strapColor: "Oystersteel",
        condition: "new",
        priceRange: "$8,100 – $8,800",
        link: "https://www.rolex.com/en-us/watches/submariner/m124060-0001",
        reaction: null,
      },
      {
        id: "var-sub-126610ln",
        modelId: "model-rolex-submariner",
        reference: "126610LN",
        label: "Date · Black",
        size: "41mm",
        dialColor: "Black",
        strapType: "bracelet",
        strapColor: "Oystersteel",
        condition: "new",
        priceRange: "$9,150 – $9,950",
        link: "https://www.rolex.com/en-us/watches/submariner/m126610ln-0001",
        reaction: null,
      },
      {
        id: "var-sub-126610lv",
        modelId: "model-rolex-submariner",
        reference: "126610LV",
        label: "Hulk · Green",
        size: "41mm",
        dialColor: "Green",
        strapType: "bracelet",
        strapColor: "Oystersteel",
        condition: "new",
        priceRange: "$14,500 – $16,000",
        link: "https://www.rolex.com/en-us/watches/submariner/m126610lv-0002",
        reaction: null,
      },
    ],
  },
  {
    id: "model-omega-aqua-terra",
    brand: "Omega",
    name: "Seamaster Aqua Terra",
    heroImage: "",
    notes: "Omega's most versatile sports watch — dressier than the Diver but still substantial. The teak-pattern dial is genuinely beautiful in person. METAS Master Chronometer certified.",
    reactionTags: [],
    topPickVariantId: null,
    rank: 2,
    variants: [
      {
        id: "var-at-41-blue",
        modelId: "model-omega-aqua-terra",
        reference: "220.10.41.21.03.004",
        label: "41mm · Blue",
        size: "41mm",
        dialColor: "Blue",
        strapType: "bracelet",
        strapColor: "Steel",
        condition: "new",
        priceRange: "$5,500 – $6,200",
        link: "https://www.omegawatches.com/watches/seamaster/aqua-terra-150m/41-mm",
        reaction: null,
      },
      {
        id: "var-at-38-silver",
        modelId: "model-omega-aqua-terra",
        reference: "220.10.38.20.02.001",
        label: "38mm · Silver",
        size: "38mm",
        dialColor: "Silver",
        strapType: "bracelet",
        strapColor: "Steel",
        condition: "new",
        priceRange: "$5,000 – $5,800",
        link: "https://www.omegawatches.com/watches/seamaster/aqua-terra-150m/38-mm",
        reaction: null,
      },
      {
        id: "var-at-41-green",
        modelId: "model-omega-aqua-terra",
        reference: "220.10.41.21.10.001",
        label: "41mm · Green",
        size: "41mm",
        dialColor: "Green",
        strapType: "bracelet",
        strapColor: "Steel",
        condition: "new",
        priceRange: "$5,500 – $6,200",
        link: "https://www.omegawatches.com/watches/seamaster/aqua-terra-150m/41-mm",
        reaction: null,
      },
    ],
  },
  {
    id: "model-tudor-bb58",
    brand: "Tudor",
    name: "Black Bay 58",
    heroImage: "",
    notes: "The smartest buy in the lineup. 39mm has vintage proportions that actually work on modern wrists. In-house movement with Rolex DNA. Hard to argue with the value.",
    reactionTags: [],
    topPickVariantId: null,
    rank: 3,
    variants: [
      {
        id: "var-bb58-navy",
        modelId: "model-tudor-bb58",
        reference: "M79030B-0001",
        label: "Navy Blue · Fabric",
        size: "39mm",
        dialColor: "Navy Blue",
        strapType: "fabric",
        strapColor: "Navy/Grey",
        condition: "new",
        priceRange: "$3,700 – $4,200",
        link: "https://www.tudorwatch.com/watches/black-bay/m79030b-0001",
        reaction: null,
      },
      {
        id: "var-bb58-black",
        modelId: "model-tudor-bb58",
        reference: "M79030N-0001",
        label: "Black · Leather",
        size: "39mm",
        dialColor: "Black",
        strapType: "leather",
        strapColor: "Black",
        condition: "new",
        priceRange: "$3,700 – $4,200",
        link: "https://www.tudorwatch.com/watches/black-bay/m79030n-0001",
        reaction: null,
      },
      {
        id: "var-bb58-burgundy",
        modelId: "model-tudor-bb58",
        reference: "M79030R-0001",
        label: "Burgundy · Bracelet",
        size: "39mm",
        dialColor: "Burgundy",
        strapType: "bracelet",
        strapColor: "Steel",
        condition: "new",
        priceRange: "$4,100 – $4,600",
        link: "https://www.tudorwatch.com/watches/black-bay/m79030r-0001",
        reaction: null,
      },
    ],
  },
  {
    id: "model-iwc-mark-xx",
    brand: "IWC",
    name: "Pilot's Watch Mark XX",
    heroImage: "",
    notes: "Clean, functional, understated. The longest power reserve in this lineup. A watch for people who don't need anyone to know what they're wearing.",
    reactionTags: [],
    topPickVariantId: null,
    rank: 4,
    variants: [
      {
        id: "var-markxx-blue",
        modelId: "model-iwc-mark-xx",
        reference: "IW328203",
        label: "Blue · Leather",
        size: "40mm",
        dialColor: "Blue",
        strapType: "leather",
        strapColor: "Brown",
        condition: "new",
        priceRange: "$4,700 – $5,200",
        link: "https://www.iwc.com/en/watch-collections/pilot-watches/iw328203",
        reaction: null,
      },
      {
        id: "var-markxx-black",
        modelId: "model-iwc-mark-xx",
        reference: "IW328201",
        label: "Black · Leather",
        size: "40mm",
        dialColor: "Black",
        strapType: "leather",
        strapColor: "Black",
        condition: "new",
        priceRange: "$4,700 – $5,200",
        link: "https://www.iwc.com/en/watch-collections/pilot-watches/iw328201",
        reaction: null,
      },
    ],
  },
  {
    id: "model-cartier-santos",
    brand: "Cartier",
    name: "Santos de Cartier",
    heroImage: "",
    notes: "The wildcard. A square case in a world of round ones — 120 years old and still looks modern. If Jack wants to stand out from every other Rolex in the room, this is the move.",
    reactionTags: [],
    topPickVariantId: null,
    rank: 5,
    variants: [
      {
        id: "var-santos-medium",
        modelId: "model-cartier-santos",
        reference: "WSSA0029",
        label: "Medium · Steel",
        size: "39.8mm",
        dialColor: "Silver",
        strapType: "bracelet",
        strapColor: "Steel",
        condition: "new",
        priceRange: "$7,300 – $8,000",
        link: "https://www.cartier.com/en-us/collections/watches/mens-watches/santos-de-cartier/wssa0029",
        reaction: null,
      },
      {
        id: "var-santos-large",
        modelId: "model-cartier-santos",
        reference: "WSSA0061",
        label: "Large · Steel",
        size: "43.5mm",
        dialColor: "Silver",
        strapType: "bracelet",
        strapColor: "Steel",
        condition: "new",
        priceRange: "$7,600 – $8,300",
        link: "https://www.cartier.com/en-us/collections/watches/mens-watches/santos-de-cartier/wssa0061",
        reaction: null,
      },
      {
        id: "var-santos-twotone",
        modelId: "model-cartier-santos",
        reference: "W2SA0006",
        label: "Medium · Two-Tone",
        size: "39.8mm",
        dialColor: "Silver",
        strapType: "bracelet",
        strapColor: "Steel & Gold",
        condition: "new",
        priceRange: "$11,500 – $12,500",
        link: "https://www.cartier.com/en-us/collections/watches/mens-watches/santos-de-cartier/w2sa0006",
        reaction: null,
      },
    ],
  },
];
